# Generated by Django 4.1.6 on 2023-02-13 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0002_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
