# Generated by Django 4.1.6 on 2023-02-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0007_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Profile Picture'),
        ),
    ]
