# Generated by Django 4.1.6 on 2023-03-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0008_alter_profile_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepicture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile pics/', verbose_name='Profile Picture'),
        ),
    ]
